// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFwg_fFJ2aq9ROlY4XSwlc-QTbLpYAc-w',
    appId: '1:1031967955031:web:6789ac646928d660c86b12',
    messagingSenderId: '1031967955031',
    projectId: 'generaworker',
    authDomain: 'generaworker.firebaseapp.com',
    storageBucket: 'generaworker.firebasestorage.app',
    measurementId: 'G-97R7PJWYJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANj4wAHlhoyf6Hbsuwj2OJUheDaRkGp-8',
    appId: '1:1031967955031:android:e6b1af2902232bcec86b12',
    messagingSenderId: '1031967955031',
    projectId: 'generaworker',
    storageBucket: 'generaworker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJvyHvav8R5IBaLzkRZzuiQZltjs8s7T8',
    appId: '1:1031967955031:ios:e11f93a019e5b128c86b12',
    messagingSenderId: '1031967955031',
    projectId: 'generaworker',
    storageBucket: 'generaworker.firebasestorage.app',
    iosBundleId: 'com.example.mobileAbz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJvyHvav8R5IBaLzkRZzuiQZltjs8s7T8',
    appId: '1:1031967955031:ios:e11f93a019e5b128c86b12',
    messagingSenderId: '1031967955031',
    projectId: 'generaworker',
    storageBucket: 'generaworker.firebasestorage.app',
    iosBundleId: 'com.example.mobileAbz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFwg_fFJ2aq9ROlY4XSwlc-QTbLpYAc-w',
    appId: '1:1031967955031:web:030d587397bed722c86b12',
    messagingSenderId: '1031967955031',
    projectId: 'generaworker',
    authDomain: 'generaworker.firebaseapp.com',
    storageBucket: 'generaworker.firebasestorage.app',
    measurementId: 'G-6R39EZKYNZ',
  );
}
